version: '3.8'

services:
  db:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    cap_add:
      - SYS_NICE

  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    env_file:
      - ./flask-app/.env
    volumes:
      - ./flask-app:/flask-app
    depends_on: 
      - db

volumes:
  mysql_data:
