version: '3.8'

services:
  flask-app:
    container_name: flask-app
    build: ./flask-app
    ports:
      - "127.0.0.1:5000:5000"
    env_file:
      - ./flask-app/.env
    volumes:
      - ./flask-app:/flask-app
    restart: "unless-stopped"
